### ISSUE TITLE
Test case 3 doesn't look right!

### ISSUE THREAD

**Issue by AbhiKafle123** [rafaybaloch/SOP-Bypass-Mini-Test-Suite#1]
`var document;`
`document = {};`
`document.domain = 'bing.com';`
`alert(document.domain);`

Boom! UXSS on every single browser out there.

**Comment by rafaybaloch** [comment]
If you run it via file:/// it would pop alert on bing.com, however on HTTP (None) - http://output.jsbin.com/wisaguqadi

Uncaught SecurityError: Failed to set the 'domain' property on 'Document': 'bing.com' is not a suffix of 'output.jsbin.com'.

**Comment by AbhiKafle123** [comment]
fixed by alerting `document.location` instead of `document.domain`
